---
name: Ted run for python migration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ted run
    steps:
      # - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      #   with:
      #     token: '${{ secrets.GITHUB_TOKEN }}'
      - name: TED run
        uses: OpenGuidou/ted@v0.9
        env:
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          EMBEDDING_DEPLOYMENT_NAME: ${{ secrets.EMBEDDING_DEPLOYMENT_NAME }}
        with:
          git-repo: "${{github.repositoryUrl}}"
          ted-flavor: unit-tests